name: check code (lint and test)

on:
  pull_request:
    branches: [main]

jobs:
  check:
    environment:
      name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
