name: deploy

on:
  # Runs after check is finished
  workflow_run:
    workflows: [check]
    types: [completed]
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy backend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}
        run: flyctl deploy --remote-only ./backend
      - name: Deploy frontend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
        run: flyctl deploy --remote-only ./frontend
